name: Build and Deploy to AWS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: dannglo/cambio-divisas

    steps:
      # Validar o checar codigo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Alistar Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Crear imagen en docker
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }} \
            -t $DOCKER_IMAGE_NAME:${{ github.sha }} .
          docker tag $DOCKER_IMAGE_NAME:${{ github.sha }} $DOCKER_IMAGE_NAME:latest

      # Subir imagen docker a dockerhub
      - name: Push Docker Image
        run: |
          docker push $DOCKER_IMAGE_NAME:${{ github.sha }}
          docker push $DOCKER_IMAGE_NAME:latest

      # Desplegar en AWS
      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          export REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
          docker compose -f docker-compose.yml up -d
